apiVersion: apps/v1
kind: Deployment
metadata:
  name: message-consumer
spec:
  replicas: 3
  selector:
    matchLabels:
      app: message-consumer
  template:
    metadata:
      labels:
        app: message-consumer
    spec:
      containers:
      - name: message-consumer
        image: message-consumer:latest
        imagePullPolicy: Never
        envFrom:
        - configMapRef:
            name: message-server-config